"""initial

Revision ID: d97d9a0f5db7
Revises: 
Create Date: 2019-01-14 13:09:17.869593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97d9a0f5db7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_musiclink',
    sa.Column('music_link', sa.Integer(), nullable=True),
    sa.Column('playlist', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_link'], ['music_link.id'], ),
    sa.ForeignKeyConstraint(['playlist'], ['playlist.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_musiclink')
    op.drop_table('playlist')
    op.drop_table('music_link')
    # ### end Alembic commands ###
